name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Try the simplified approach first
      - name: Build and push Docker image (simplified approach)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.custom
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/juangpt:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
        continue-on-error: true
        id: build-simple

      # If simplified approach fails, try the full build with increased memory
      - name: Build and push Docker image (full build with increased memory)
        if: steps.build-simple.outcome != 'success'
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/juangpt:latest
          build-args: |
            NODE_OPTIONS=--max-old-space-size=12288
          cache-from: type=gha
          cache-to: type=gha,mode=max
